'use strict';

module.exports = {
 up: queryInterface => queryInterface.bulkInsert('user', [{
   id:2,
   user_name:'aparna',
   latitude:12.12910,
   longitude:79.46,
   inride:true,
   createdAt: new Date(),
        updatedAt: new Date(),
 },
 {
     id:3,
     user_name:'rajasekar',
     latitude:12.1452,
     longitude:79.571,
     inride:false,
     createdAt: new Date(),
        updatedAt: new Date(),
 },

 {
     id:4,
     user_name:'appu',
     latitude:12.010,
     longitude:79.68,
     inride:false,
     createdAt: new Date(),
    updatedAt: new Date(),
 },
 {
     id:5,
     user_name:'poo',
     latitude:11.688,
     longitude:79.615,
     inride:false,
     createdAt: new Date(),
        updatedAt: new Date(),
 },
 {
     id:6,
     user_name:'sajina',
     latitude:11.76,
     longitude:79.79,
     inride:false,
     createdAt: new Date(),
    updatedAt: new Date(),
 },
 {
     id:7,
     user_name:'ganesh',
     latitude:14.08,
     longitude:52.03,
     inride:false,
     createdAt: new Date(),
        updatedAt: new Date(),
 },
 {
     id:8,
     user_name:'priya',
     latitude:14.08,
     longitude:52.03,
      inride:false,
     createdAt: new Date(),
      updatedAt: new Date(),
 },
 {
     id:9,
     user_name:'kupta',
     latitude:14.08,
     longitude:52.03,
     inride:false,
     createdAt: new Date(),
        updatedAt: new Date(),
 },
 {
     id:10,
     user_name:'somu',
     latitude:14.08,
     longitude:52.03,
     inride:false,
     createdAt: new Date(),
        updatedAt: new Date(),
 },


],
  {}),
};
